---
title: ""
output:
  html_document:
    includes:
      in_header: hero-image.html
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-7WHKSS4NSD"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7WHKSS4NSD');
</script>

<br>

## 弁護士　

## 髙　世羅

<br>

### [経歴]{.ul}

<br>

長尾谷高校　卒業

同志社大学法学部　卒業

大阪大学法科大学院　修了

司法試験　合格

最高裁判所司法研修所（高松地方裁判所配属） 修了

<br>

### [取り扱い分野]{.ul}

<br>

一般民事, 交通事故, 離婚・男女問題, 刑事弁護・少年事件, 債務整理・過払い金請求, B型肝炎訴訟, 遺産相続, 成年後見, 労働問題, 労働災害, 債権回収, 学校問題, 削除請求, 消費者被害, 一般企業法務, 危機管理・不祥事対応, 建物明渡訴訟, 行政事件

<br>

### [メッセージ]{.ul}

<br>

私は、高校を辞めた後、解体作業や足場を組む仕事をしながら半年間ほどその日暮らしをしておりました。\
そんな折、親しい友人が逮捕され、その友人についてくださった国選付添人の熱心な弁護活動を見て、弁護士になることを決意し、晴れて弁護士となることができました。

私自身マイノリティに属しており、弁護士になれた以上、法的に困っている人・社会的に弱い立場の人を守るべく闘うことが私の使命だと考えております。\
いい意味で弁護士らしくない弁護士として、紛争を解決すべく誠心誠意心を込めてお客様に寄り添った弁護活動をしていきたいです。

司法試験受験後、高校時代にやっていた総合格闘技を再開いたしました。\
今後も格闘技を続けていきたいと考えており、これからは色々なものと闘う弁護士として精進していきたいと考えておりますので、よろしくお願いいたします。
